Repository DeveloperAcademy-POSTECH/MacC-TeamID-TDAA, pull requests merged in 2022-10, with the labels that each got.

#14 Feat/#6 MyDiariesView UI 구현
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.xcworkspace/xcuserdata/woo0.xcuserdatad/UserInterfaceState.xcuserstate
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/xcuserdata/woo0.xcuserdatad/xcschemes/xcschememanagement.plist
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/AppDelegate.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/GoogleService-Info.plist
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/DiaryCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyDiariesViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/TabBarController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/DiaryCollectionHeaderView.swift
Labels: enhancement

#15 Feat/9 SignInView 버튼 UI 구현, SnapKit 학습 내용 아카이빙
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyDiariesViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/SignIn/SignInTestViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/SignIn/SignInViewController.swift
Labels: documentation, enhancement, D-2

#16 Feat/13 글 작성 페이지 UI, 스티커 넣기 기능 규현
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/PageViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/TabBarController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerBorderView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerContollerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerView.swift
Labels: enhancement, D-2

#17 pbxfile 오류 긴급수정
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
Labels: bug, D-0

#23 지도 툴 기능 구현
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/CollectionView+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/TableView+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIView+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/MapSearchViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerView.swift
Labels: D-1

#25 Feat/#20 이미지 스티커 기능 구현
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerView.swift
Labels: enhancement, D-1

#29 Feat/#21 스티커 피커 기능 구현
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/dumplingSticker.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/dumplingSticker.imageset/dumplingSticker.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/fireSticker.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/fireSticker.imageset/fireSticker.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/hamburgerSticker.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/hamburgerSticker.imageset/hamburgerSticker.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/pizzaSticker.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/pizzaSticker.imageset/pizzaSticker.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/waffleSticker.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/waffleSticker.imageset/waffleSticker.png
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/Page/StickerPickerCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/HalfModalPresentationController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/StickerPickerViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerView.swift
Labels: enhancement, D-1

#31 Feat/10 Diary Config View 제목, 위치검색 버튼 추가
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/DiaryConfigCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/SignIn/SignInTestViewController.swift
Labels: enhancement, D-2

#30 Feat/6 MyDiariesView 수정
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.xcworkspace/xcuserdata/woo0.xcuserdatad/UserInterfaceState.xcuserstate
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/xcuserdata/woo0.xcuserdatad/xcschemes/xcschememanagement.plist
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/DiaryCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/FirebaseClient.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/MyDiariesViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/DiaryModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyDiariesViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyDiariesViewCustomModalVC.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/DiaryCollectionHeaderView.swift
Labels: enhancement, D-1

#32 Feat/#22 텍스트 추가 도구 구현, StickerView 리팩토링
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/PageViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/ImageStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/MapStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerBorderView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/TextStickerView.swift
Labels: enhancement, D-1

#34 Feat/10 diary config view 캘린더 추가
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/SceneDelegate.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/DiaryConfigCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/Date+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarDateCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarPickerFooterView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarPickerHeaderView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarPickerViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/Day.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/MonthMetadata.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/SignIn/SignInViewController.swift
Labels: enhancement, D-3

#38 Page View DB연동
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/FirebaseClient.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/FirebaseStorage.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIView+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/DiaryModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/PageViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/ImageStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/MapStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerViewData.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/TextStickerView.swift
Labels: enhancement, D-1

#39 Feat/6 MyDiariesView 수정
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.xcworkspace/xcuserdata/woo0.xcuserdatad/UserInterfaceState.xcuserstate
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/100.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/1024.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/114.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/120.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/144.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/152.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/167.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/180.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/20.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/29.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/40.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/50.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/57.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/58.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/60.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/72.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/76.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/80.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/87.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/로고임시용.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/TabBarIcon/notPress/notPressProfile.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/TabBarIcon/notPress/notPressProfile.imageset/notPresProfile.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/TabBarIcon/notPress/notPressProfile.imageset/notPresProfile@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/TabBarIcon/notPress/notPressProfile.imageset/notPresProfile@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Info.plist
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Fonts/EF_Diary.ttf
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/DiaryCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/MyDiaries/DiaryCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/FirestoreClient.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/MyDiariesViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIImageView+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/DiaryCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/User.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyDiariesViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyDiariesViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/TabBarController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/MyDiaries/DiaryCollectionHeaderView.swift
Labels: enhancement, design, D-1

#41 Feat/페이지뷰 페이지 추가 기능
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/FirebaseClient.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/PageViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerView.swift
Labels: enhancement, D-1

#42 Feat/11 MyDiaryPagesView UI 및 기능 추가
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/DiaryConfigCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/PopUpViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/SignIn/SignInTestViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/SignIn/SignInViewController.swift
Labels: enhancement, D-1

#45 Feat/6 my home view
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.xcworkspace/xcuserdata/woo0.xcuserdatad/UserInterfaceState.xcuserstate
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/MyHome/DiaryCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/FirestoreClient.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/DiaryCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/DiaryModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/MapData.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyHomeViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyPlaceViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyAlbumViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyHomeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyHomeViewCustomModalVC.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyPlaceViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyPlacesViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/TabBarController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/MyHome/DiaryCollectionHeaderView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Place/MapView.swift
Labels: enhancement, D-0

#49 #43 #47 페이지뷰 커스텀 모달 + 기타 페이지 뷰 기능
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/ImageManager.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/PageViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyHomeViewCustomModalVC.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/PopUpViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/ImageStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/MapStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/TextStickerView.swift
Labels: enhancement, D-1

#48 Feat/7 MyPlaceView
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.xcworkspace/xcuserdata/woo0.xcuserdatad/UserInterfaceState.xcuserstate
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyHomeViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyPlaceViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyHomeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyPlaceViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/TabBarController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/MyHome/DiaryCollectionHeaderView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Place/CustomAnnotationView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Place/CustomClusterAnnotationView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Place/MapView.swift
Labels: enhancement, D-0

#50 Feat/ 11 & 36 다이어리 데이터 베이스 연결, 캘린더 날짜 선택 기능 개선
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/DiaryConfigCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/Date+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/String+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarPickerFooterView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarPickerHeaderView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarPickerViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyHomeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/SignIn/SignInTestViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/SignIn/SignInViewController.swift
Labels: enhancement, D-1

#53 Feat/10&11&36 썸네일 이미지, 캘린더 뷰, 다이어리 편집 화면 수정
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/DiaryConfigCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/Date+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarDateCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarPickerFooterView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarPickerHeaderView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarPickerViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/Day.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyHomeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/PopUpViewController.swift
Labels: enhancement, D-1

#54 Feat/#44 page view hifi반영
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIColor+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIFont+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/DiaryModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/PageViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/MapStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerBorderView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerContollerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/TextStickerView.swift
Labels: enhancement, D-0

#57 Feat/8 MyAlbumView
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.xcworkspace/xcuserdata/woo0.xcuserdatad/UserInterfaceState.xcuserstate
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/MyAlbum/MyAlbumCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/MyAlbum/MyAlbumPhotoCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/MyAlbum/MyAlbumTitleCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/MyHome/DiaryCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/FirebaseStorage.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/FirestoreClient.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/AlbumData.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyAlbumViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyAlbumPhotoViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyAlbumViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyHomeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyPlaceViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/TabBarController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Place/CustomClusterAnnotationView.swift
Labels: enhancement, D-0

#60 Feat/58 qa수정사항
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.xcworkspace/xcuserdata/woo0.xcuserdatad/UserInterfaceState.xcuserstate
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/MyAlbum/MyAlbumTitleCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/LoadingIndicator.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyAlbumViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyHomeViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyPlaceViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyAlbumPhotoViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyAlbumViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyHomeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyHomeViewCustomModalVC.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyPlaceViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/MyHome/DiaryCollectionHeaderView.swift
Labels: enhancement, D-0

#59 Feat/36 캘린더 UI 구현
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/calender/calendarCheckColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/calender/calendarSubTextColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/calender/calendarTermColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/calender/calendarTextColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/signInTitleColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/signInLogo.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/signInLogo.imageset/signInLogo@1x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/signInLogo.imageset/signInLogo@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/signInLogo.imageset/signInLogo@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/DiaryConfigCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarDateCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarPickerFooterView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarPickerHeaderView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarPickerViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/TabBarController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/SignIn/SignInViewController.swift
Labels: enhancement, D-1

#62 Feat/#55 mypage 구현
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Stamp/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Stamp/stampLayout.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Stamp/stampLayout.imageset/stampLayout.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Stamp/stampLayout.imageset/stampLayout@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Stamp/stampLayout.imageset/stampLayout@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/MyPage/TravelsCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/FirestoreClient.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIColor+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIFont+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIView+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/User.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyPageViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/PageViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyPageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyPageViewControllers/MyPageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyPageViewControllers/SetProfileImageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/StickerPickerViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/ImageStickerView.swift
Labels: enhancement, D-0

#65 [Fix] #63 에셋 추가 및 수정
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/buttonColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/calendarSubTextColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/calendarTermColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/calendarWeeklyGrayColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/calender/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/calender/calendarSubTextColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/calender/calendarTermColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/darkgrayColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/sandbrownColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/startDateColor.colorset/Contents.json
Labels: design

#67 [fix] #66 에셋 추가 수정 요소들
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/100.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/1024.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/114.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/120.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/144.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/152.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/167.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/180.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/20.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/29.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/40.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/50.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/57.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/58.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/60.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/72.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/76.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/80.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/AppIcon.appiconset/87.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryBrown.imageset/diaryBrown.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryBrown.imageset/diaryBrown@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryBrown.imageset/diaryBrown@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryPink.imageset/diaryPink.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryPink.imageset/diaryPink@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryPink.imageset/diaryPink@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/signInLogo.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/signInLogo.imageset/signInLogo.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/signInLogo.imageset/signInLogo@1x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/signInLogo.imageset/signInLogo@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/signInLogo.imageset/signInLogo@3x.png
Labels: design

#68 Feat/#55 마이페이지 테이블 뷰 기능
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Stamp/profileImage.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Stamp/profileImage.imageset/profileImage.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Stamp/profileImage.imageset/profileImage@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Stamp/profileImage.imageset/profileImage@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/MyHome/DiaryCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/MyPage/MenuTableViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/FirestoreClient.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyHomeViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyPageViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/TabBarController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyPageViewControllers/MyPageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/SignIn/SignInViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerView.swift
Labels: bug, D-0

#69 Fix/58 버그수정
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Stamp/stampLayout.imageset/stampLayout.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Stamp/stampLayout.imageset/stampLayout@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Stamp/stampLayout.imageset/stampLayout@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/MyAlbum/MyAlbumTitleCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/FirestoreClient.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIImageView+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIView+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyAlbumViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyHomeViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyAlbumPhotoViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyAlbumViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyHomeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyPlaceViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Place/CustomAnnotationView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Place/CustomClusterAnnotationView.swift
Labels: bug, D-0

#70 Fix/#61 수정사항 반영
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIColor+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIFont+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/DiaryModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyPageViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarDateCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarPickerFooterView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarPickerHeaderView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarPickerViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyPageViewControllers/MyPageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/SignIn/SignInViewController.swift
Labels: enhancement, D-0

#72 [fix] #58 버그수정
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/FirestoreClient.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyAlbumViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyHomeViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyHomeViewController.swift
Labels: bug, D-0

#74 [Feat] #73 이미지 디스크 캐시 구현
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/ImageManager.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIImageView+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyAlbumViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyPageViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/ImageStickerView.swift
Labels: enhancement, D-2

#76 [Feat] #75 지도 검색 결과 주소 표시
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/Page/MapSearchResultTableViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/MapSearchViewController.swift
Labels: enhancement, D-2

#77 앱 평가하기 링크 수정
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyPageViewControllers/MyPageViewController.swift
Labels: bug, D-2

#83 Fix/81 sign in view update
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/SignIn/SignInViewController.swift
Labels: enhancement, D-2

#85 [feat] #78 AlbumPhotoView 확대 축소 구현
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/MyAlbum/MyAlbumPhotoCollectionViewCell.swift
Labels: enhancement, D-1

#87 Feat/86 MyHomeView
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Button/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Button/closeButton.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Button/closeButton.imageset/xButton.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Button/closeButton.imageset/xButton@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Button/closeButton.imageset/xButton@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Button/plusButton.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Button/plusButton.imageset/plusButton.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Button/plusButton.imageset/plusButton@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Button/plusButton.imageset/plusButton@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/plusButton.imageset/plusButton.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/plusButton.imageset/plusButton@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/plusButton.imageset/plusButton@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/MyAlbum/MyAlbumTitleCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/MyHome/DiaryCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/Notification+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIColor+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyAlbumViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyHomeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyPlaceViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/TabBarController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/PopUpViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Place/MapView.swift
Labels: enhancement, D-1

#89 Add/#88 add assets for halloween
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/broom.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/broom.imageset/broom.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/broom.imageset/broom@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/broom.imageset/broom@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost1.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost1.imageset/ghost1.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost1.imageset/ghost1@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost1.imageset/ghost1@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost2.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost2.imageset/ghost2.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost2.imageset/ghost2@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost2.imageset/ghost2@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost3.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost3.imageset/ghost3.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost3.imageset/ghost3@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost3.imageset/ghost3@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost4.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost4.imageset/ghost4.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost4.imageset/ghost4@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost4.imageset/ghost4@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost5.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost5.imageset/ghost5.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost5.imageset/ghost5@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost5.imageset/ghost5@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost6.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost6.imageset/ghost6.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost6.imageset/ghost6@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost6.imageset/ghost6@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost7.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost7.imageset/ghost7.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost7.imageset/ghost7@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/ghost7.imageset/ghost7@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/pot.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/pot.imageset/pot.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/pot.imageset/pot@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/pot.imageset/pot@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/pumpkin1.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/pumpkin1.imageset/pumpkin1.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/pumpkin1.imageset/pumpkin1@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/pumpkin1.imageset/pumpkin1@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/pumpkin2.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/pumpkin2.imageset/pumpkin2.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/pumpkin2.imageset/pumpkin2@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/pumpkin2.imageset/pumpkin2@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/pumpkin3.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/pumpkin3.imageset/pumpkin3.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/pumpkin3.imageset/pumpkin3@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/pumpkin3.imageset/pumpkin3@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/wizardHat.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/wizardHat.imageset/wizardHat.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/wizardHat.imageset/wizardHat@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/OnlyForHalloween/wizardHat.imageset/wizardHat@3x.png
Labels: D-1

#93 [feat] #90 앨범 화면 미선택 앨범 색상 수정
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/calendarWeeklyGrayColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/MyAlbum/MyAlbumTitleCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIColor+.swift
Labels: enhancement, D-1

#91 [Feat] #86 MyHomeView
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Button/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Button/closeButton.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Button/closeButton.imageset/xButton.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Button/closeButton.imageset/xButton@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Button/closeButton.imageset/xButton@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Button/plusButton.imageset/plusButton.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Button/plusButton.imageset/plusButton@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Button/plusButton.imageset/plusButton@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/plusButton.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/plusButton.imageset/plusButton.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/plusButton.imageset/plusButton@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/plusButton.imageset/plusButton@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/MyAlbum/MyAlbumTitleCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/MyHome/DiaryCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/Notification+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIColor+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyAlbumViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyHomeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyPlaceViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/TabBarController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/PopUpViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Place/MapView.swift
Labels: enhancement, D-1

#92 Feat/#79 my place view
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyPlaceViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Place/CustomAnnotationView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Place/CustomClusterAnnotationView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Place/MapView.swift
Labels: enhancement, D-1

#94 Fix/#80 수정사항 반영
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/DiaryConfig/DiaryConfigCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/PageViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarPickerViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewModel.swift
Labels: enhancement, D-1
