Repository DeveloperAcademy-POSTECH/MacC-TeamID-TDAA, pull requests merged in 2022-11, with the labels that each got.

#104 Refactor/#98 MyHomeView RxSwift+MVVM 리팩토링
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/xcuserdata/woo0.xcuserdatad/xcschemes/xcschememanagement.plist
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/MyHome/DiaryCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/FirestoreClient.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/DiaryCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/DiarySection.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/DiaryCollectionViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyHomeViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyPageViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyHomeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/MyHome/CollectionEmptyView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/MyHome/DiaryCollectionHeaderView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/MyHome/DiaryCollectionView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/MyHome/HomeAddDiaryButtonView.swift
Labels: D-1, Refactor

#110 Refactor/#99 refactor sticker views
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/DiaryModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ErrorMessage.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/User.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/PageViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/ImageStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/MapStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerBorderView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerContollerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerViewData.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/TextStickerView.swift
Labels: enhancement, D-1, Refactor

#106 Refactor/#100 DiaryConfigView RxSwift + MVVM 리팩토링
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/DiaryConfig/DiaryConfigCellViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/DiaryConfig/DiaryConfigCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarView/CalendarDateCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarView/CalendarPickerFooterView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarView/CalendarPickerHeaderView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarView/CalendarPickerViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarView/Day.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarView/MonthMetadata.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryColorCollectionView/DiaryColorCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryColorCollectionView/DiaryColorCellViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryColorCollectionView/DiaryColorCollectionView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryColorCollectionView/DiaryColorCollectionViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyHomeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/SignIn/SignInTestViewController.swift
Labels: D-2, Refactor

#116 Feat/#111 album view
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/Notification+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/AlbumCollectionViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyHomeViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyAlbumPhotoViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyAlbumViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyHomeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/TabBarController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyPageViewControllers/MyPageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/SignIn/SignInViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Album/AlbumCollectionView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Album/PhotoCollectionView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/MyHome/CollectionEmptyView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/MyHome/DiaryCollectionView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/MyHome/HomeButtonView.swift
Labels: enhancement, D-1, Refactor

#118 add/ #117-add assets
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryBlack.imageset/diaryBlack.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryBlack.imageset/diaryBlack@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryBlack.imageset/diaryBlack@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryBlue.imageset/diaryBlue.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryBlue.imageset/diaryBlue@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryBlue.imageset/diaryBlue@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryBrown.imageset/diaryBrown.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryBrown.imageset/diaryBrown@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryBrown.imageset/diaryBrown@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryGreen.imageset/diaryGreen.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryGreen.imageset/diaryGreen@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryGreen.imageset/diaryGreen@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryOrange.imageset/diaryOrange.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryOrange.imageset/diaryOrange@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryOrange.imageset/diaryOrange@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryPink.imageset/diaryPink.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryPink.imageset/diaryPink@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryPink.imageset/diaryPink@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryPurple.imageset/diaryPurple.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryPurple.imageset/diaryPurple@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryPurple.imageset/diaryPurple@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryRed.imageset/diaryRed.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryRed.imageset/diaryRed@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryRed.imageset/diaryRed@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryWhite.imageset/diaryWhite.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryWhite.imageset/diaryWhite@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryWhite.imageset/diaryWhite@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryYellow.imageset/diaryYellow.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryYellow.imageset/diaryYellow@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryYellow.imageset/diaryYellow@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/appBackgroundColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/separatorColor.colorset/Contents.json
Labels: design

#119 Feat/#114 page view mode 구현
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/FirebaseStorage.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/FirestoreClient.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/CALayer+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/String+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ErrorMessage.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/PageViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewModeCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewModeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/ImageStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerView.swift
Labels: enhancement, D-1

#122 [Add] #121 에셋 추가
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/defaultBottomcover.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/defaultBottomcover.imageset/defaultBottomcover.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/defaultBottomcover.imageset/defaultBottomcover@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/defaultBottomcover.imageset/defaultBottomcover@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryBlack.imageset/diaryBlack.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryBlack.imageset/diaryBlack@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryBlack.imageset/diaryBlack@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryBlue.imageset/diaryBlue.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryBlue.imageset/diaryBlue@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryBlue.imageset/diaryBlue@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryBrown.imageset/diaryBrown.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryBrown.imageset/diaryBrown@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryBrown.imageset/diaryBrown@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryGreen.imageset/diaryGreen.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryGreen.imageset/diaryGreen@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryGreen.imageset/diaryGreen@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryOrange.imageset/diaryOrange.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryOrange.imageset/diaryOrange@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryOrange.imageset/diaryOrange@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryPink.imageset/diaryPink.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryPink.imageset/diaryPink@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryPink.imageset/diaryPink@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryPurple.imageset/diaryPurple.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryPurple.imageset/diaryPurple@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryPurple.imageset/diaryPurple@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryRed.imageset/diaryRed.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryRed.imageset/diaryRed@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryRed.imageset/diaryRed@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryWhite.imageset/diaryWhite.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryWhite.imageset/diaryWhite@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryWhite.imageset/diaryWhite@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryYellow.imageset/diaryYellow.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryYellow.imageset/diaryYellow@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Diarycover/diaryYellow.imageset/diaryYellow@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/diaryDaysDefault.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/diaryDaysDefault.imageset/diaryDaysDefault.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/diaryDaysDefault.imageset/diaryDaysDefault@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/diaryDaysDefault.imageset/diaryDaysDefault@3x.png
Labels: D-0

#120 Feat/#109 다이어리 생성 / 수정 화면 구현
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/diaryColor/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/diaryColor/diaryBlackColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/diaryColor/diaryBlueColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/diaryColor/diaryBrownColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/diaryColor/diaryGreenColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/diaryColor/diaryOrangeColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/diaryColor/diaryPinkColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/diaryColor/diaryPurpleColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/diaryColor/diaryRedColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/diaryColor/diaryWhiteColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/diaryColor/diaryYellowColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/requiredItemsColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/selectImage.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/selectImage.imageset/selectImage@1x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/selectImage.imageset/selectImage@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/selectImage.imageset/selectImage@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/DiaryConfig/DiaryConfigCellViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/DiaryConfig/DiaryConfigCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/NSMutableAttributedString+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIColor+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIImage+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/DiaryModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryColorCollectionView/DiaryColorCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryColorCollectionView/DiaryColorCellViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryColorCollectionView/DiaryColorCollectionView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryColorCollectionView/DiaryColorCollectionViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewController.swift
Labels: enhancement, D-1

#131 Feat/#115 text sticker view 2차 스프린트 기능 반영
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/Page/PageViewModeCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/String+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/PageViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewModeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/ImageStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerViewData.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/TextStickerView.swift
Labels: enhancement, D-0

#132 Feat/#108 전체 일차 및 날짜 다이어리 화면 구현
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/separatorColor2.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIColor+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIFont+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/DiaryDayModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/DiaryModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyHomeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryDays/DiaryDaysCollectionView/DiaryDaysCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryDays/DiaryDaysCollectionView/DiaryDaysCollectionView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryDays/DiaryDaysCollectionView/DiaryDaysCollectionViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryDays/MyDiaryDaysModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryDays/MyDiaryDaysViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryDays/MyDiaryDaysViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/PopUpViewController.swift
Labels: enhancement, D-1

#135 Feat/#113 HomeView UI 수정
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/AppDelegate.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/MyHome/DiaryCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIFont+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/DiaryCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/DiarySection.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/DiaryCollectionViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyHomeViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyHomeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Map/MapListViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/PopUpViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyPageViewControllers/MyPageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/MyHome/DiaryCollectionView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/MyHome/HomeButtonView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Place/SegmentedControlView.swift
Labels: enhancement, D-0

#136 Feat/#134 다이어리 일차 보는 뷰
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/MapModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyHomeViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Album/MyAlbumPhotoViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/DiaryConfigViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyHomeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Main/MyPlaceViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryDays/DiaryDaysCollectionView/DiaryDaysCollectionViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryDays/MyDiaryDaysModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryDays/MyDiaryDaysViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryDays/MyDiaryDaysViewModel.swift
Labels: enhancement, D-1

#137 Design/#133 hifi 디자인 반영
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/customColor/stickerBackgroundColor.colorset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/Page/PageCollectionViewHeaderCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/Page/PageViewModeCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIColor+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIView+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MyPageViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/PageViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyPageViewControllers/MyPageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyPageViewControllers/SetProfileImageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewModeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/MapStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerViewData.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/TextStickerView.swift
Labels: bug, design, D-1

#142 [Feat] #141 화면 데이터 전달 방식 변경
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryDays/MyDiaryDaysModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryDays/MyDiaryDaysViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryDays/MyDiaryDaysViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryPages/MyDiaryPagesViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewModeViewController.swift
Labels: enhancement

#147 Feat/#139 map view수정사항
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/Notification+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/MapModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/MapViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Map/MapHalfModalPresentationController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Map/MapListViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryDays/MyDiaryDaysViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Place/MapListView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Place/MapView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Place/SegmentedControlView.swift
Labels: enhancement, D-1

#149 Fix/#144 Page View Bug Fix
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/Page/PageViewModeCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/PageViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageEditModeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewModeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/MapStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/StickerViewData.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Sticker/TextStickerView.swift
Labels: bug, D-0, Refactor

#151 Feat/#140 UI 수정 [캘린더 년/월 선택, ToastMessage, Segmented Control, 로그인 로딩]
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/Date+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIView+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarView/CalendarPickerFooterView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarView/CalendarPickerHeaderView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarView/CalendarPickerViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/DiaryConfig/CalendarView/CalendarYearPickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryDays/DiaryDaysSegmentedControlView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyDiaryDays/MyDiaryDaysViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/SignIn/SignInViewController.swift
Labels: enhancement, D-1

#155 Design/#143 3차 스프린트 디자인 반영
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/passport2.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/passport2.imageset/passfort2.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/passport2.imageset/passfort2@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/passport2.imageset/passfort2@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/Page/StickerPickerCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyPageViewControllers/MyPageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/MyPageViewControllers/SetProfileImageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewModeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/StickerPickerViewController.swift
Labels: design, D-0

#157 [Add] #156 에셋 추가 및 수정
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/camera.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/camera.imageset/camera.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/camera.imageset/camera@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/camera.imageset/camera@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/fork.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/fork.imageset/fork.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/fork.imageset/fork@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/fork.imageset/fork@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/knife.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/knife.imageset/knife.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/knife.imageset/knife@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/knife.imageset/knife@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/passport 1.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/passport 1.imageset/passport.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/passport 1.imageset/passport@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/passport 1.imageset/passport@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/passport.imageset/passfort.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/passport.imageset/passfort@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/passport.imageset/passfort@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/passport2.imageset/passfort2.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/passport2.imageset/passfort2@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/passport2.imageset/passfort2@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/plate.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/plate.imageset/plate.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/plate.imageset/plate@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/plate.imageset/plate@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/manLong.imageset/manLong.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/manLong.imageset/manLong@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/manLong.imageset/manLong@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/manLong2.imageset/manLong2.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/manLong2.imageset/manLong2@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/manLong2.imageset/manLong2@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/manShort.imageset/manShort.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/manShort.imageset/manShort@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/manShort.imageset/manShort@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/manShort2.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/manShort2.imageset/manShort2.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/manShort2.imageset/manShort2@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/manShort2.imageset/manShort2@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/womanLong.imageset/womanLong.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/womanLong.imageset/womanLong@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/womanLong.imageset/womanLong@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/womanLong2.imageset/womanLong2.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/womanLong2.imageset/womanLong2@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/womanLong2.imageset/womanLong2@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/womanShort.imageset/womanShort.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/womanShort.imageset/womanShort@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/womanShort.imageset/womanShort@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/womanshort2.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/womanshort2.imageset/womanshort2.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/womanshort2.imageset/womanshort2@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/character/womanshort2.imageset/womanshort2@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/mapListIcons/defaultIcon.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/mapListIcons/defaultIcon.imageset/defaultIcon.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/mapListIcons/defaultIcon.imageset/defaultIcon@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/mapListIcons/defaultIcon.imageset/defaultIcon@3x.png
Labels: enhancement, design, D-0

#159 PageView 리팩토링, 버그 수정
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/passport.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/passport.imageset/passport.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/passport.imageset/passport@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Assets.xcassets/Sticker/passport.imageset/passport@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/PageSection.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/PageEditModeViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/ViewModels/PageViewModeViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageEditModeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/PageViewModeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Page/StickerPickerViewController.swift
Labels: bug, design, D-1, Refactor

#160 Feat/#148피드백수정사항
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Cells/Map/MapListCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Models/MapCategory.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Map/MapListViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Place/MapListView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Place/MapView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Place/SegmentedControlView.swift
Labels: bug, enhancement, D-1

#162 [feat] #161 MapView region 수정
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/ViewControllers/Map/MapListViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Place/MapView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Views/Place/SegmentedControlView.swift
Labels: enhancement, D-0

#168 [Feat] #153 Deep Link (Firebase Dynamic Link 추가)
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Info.plist
  MacC-GoldenRatio/MacC-GoldenRatio/MacC-GoldenRatio.entitlements
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/AppDelegate.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/SceneDelegate.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/DynamicLinkBuilder.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/String+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIKit/UIApplication+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/ViewController/MyDiaryDaysViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/HomeScene/ViewController/MyHomeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/SignInScene/ViewController/SignInViewController.swift
Labels: enhancement, D-2

#169 Feat/#165 스티커수평정렬&햅틱피드백
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/View/StickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/View/StickerViewData.swift
Labels: enhancement, D-1

#171 [Add] #170 에셋 추가
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/Button/minusButton.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/Button/minusButton.imageset/minusButton.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/Button/minusButton.imageset/minusButton@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/Button/minusButton.imageset/minusButton@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/Toolbox/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/Toolbox/stickerTool.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/Toolbox/stickerTool.imageset/stickerTool.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/Toolbox/stickerTool.imageset/stickerTool@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/Toolbox/stickerTool.imageset/stickerTool@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/Toolbox/textTool.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/Toolbox/textTool.imageset/textTool.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/Toolbox/textTool.imageset/textTool@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/Toolbox/textTool.imageset/textTool@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin1.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin1.imageset/mapPin1.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin1.imageset/mapPin1@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin1.imageset/mapPin1@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin10.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin10.imageset/mapPin10.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin10.imageset/mapPin10@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin10.imageset/mapPin10@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin2.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin2.imageset/mapPin2.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin2.imageset/mapPin2@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin2.imageset/mapPin2@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin3.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin3.imageset/mapPin3.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin3.imageset/mapPin3@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin3.imageset/mapPin3@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin4.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin4.imageset/mapPin4.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin4.imageset/mapPin4@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin4.imageset/mapPin4@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin5.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin5.imageset/mapPin5.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin5.imageset/mapPin5@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin5.imageset/mapPin5@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin6.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin6.imageset/mapPin6.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin6.imageset/mapPin6@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin6.imageset/mapPin6@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin7.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin7.imageset/mapPin7.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin7.imageset/mapPin7@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin7.imageset/mapPin7@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin8.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin8.imageset/mapPin8.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin8.imageset/mapPin8@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin8.imageset/mapPin8@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin9.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin9.imageset/mapPin9.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin9.imageset/mapPin9@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/mapPin/mapPin9.imageset/mapPin9@3x.png
Labels: enhancement, design

#172 Image Picker 라이브러리 추가 및 반영
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/License.txt
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/YPImagePickerManager.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/ViewController/PageEditModeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/ViewModel/StickerViewData.swift
Labels: enhancement, D-2

#174 [Feat] #167 다이어리 썸네일 선택 뷰 및 썸네일 적용 구현
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/GoogleService-Info.plist
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIKit/UIFont+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Model/DiaryModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/Common/Model/AlbumData.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/Common/View/AlbumCollectionView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/Common/View/Cell/MyAlbumCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/Common/ViewModel/AlbumCollectionViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryConfigScene/ViewController/DiaryConfigViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryConfigScene/ViewModel/DiaryConfigViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/Model/MyDiaryDaysModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/ViewModel/DiaryDaysCollectionViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/ViewModel/MyAlbumViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/ViewModel/MyDiaryDaysViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/ViewController/PageViewModeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/ThumbnailConfigScene/View/ThumbnailPreviewView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/ThumbnailConfigScene/ViewController/ThumbnailConfigViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/ThumbnailConfigScene/ViewModel/ThumbnailConfigViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/ThumbnailConfigScene/ViewModel/ThumbnailPreviewViewModel.swift
Labels: enhancement, D-2

#176 [design] #173 스티커 도구 버튼 이미지 변경
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/ViewController/PageEditModeViewController.swift
Labels: design, D-1

#175 Feat/#164 Home DiaryList 기능 추가
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/RemoveButton.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIKit/UIFont+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIKit/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Model/DiaryCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/View/SegmentedControlView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/ViewController/MyAlbumPhotoViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/HomeScene/View/Cell/DiaryCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/HomeScene/View/DiaryCollectionHeaderView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/HomeScene/View/DiaryCollectionView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/HomeScene/View/FilterButton.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/HomeScene/ViewController/MyHomeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/HomeScene/ViewModel/DiaryCollectionViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/HomeScene/ViewModel/MyHomeViewModel.swift
Labels: enhancement, D-1, Refactor

#179 [feat] #164 Home 및 Map UI 수정
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/SceneDelegate.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIKit/UIFont+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIKit/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/Model/MapModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/View/MapView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/HomeScene/View/Cell/DiaryCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/HomeScene/View/DiaryCollectionView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/HomeScene/ViewController/MyHomeViewController.swift
Labels: enhancement, D-0

#178 [Feat] #174 다이어리 생성/수정 YPImagePicker 적용
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/Diarycover/selectImage.imageset/Contents.json
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/Diarycover/selectImage.imageset/selectImage@1x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/Diarycover/selectImage.imageset/selectImage@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/Diarycover/selectImage.imageset/selectImage@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/selectImage.imageset/selectImage.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/selectImage.imageset/selectImage@2x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/Assets.xcassets/selectImage.imageset/selectImage@3x.png
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/YPImagePickerManager.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryConfigScene/View/Cell/DiaryConfigCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryConfigScene/ViewController/DiaryConfigViewController.swift
Labels: enhancement, D-2
