Repository DeveloperAcademy-POSTECH/MacC-TeamID-TDAA, pull requests merged in 2022-12, with the labels that each got.

#184 [Feat] #183 Localizing
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/SceneDelegate.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/en.lproj/Localizable.strings
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/ko.lproj/LaunchScreen.strings
  MacC-GoldenRatio/MacC-GoldenRatio/Resources/ko.lproj/Localizable.strings
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/DynamicLinkBuilder.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/Date+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/String+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/Common/View/AlbumCollectionView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/Common/ViewController/PopUpViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryConfigScene/Model/DiaryConfigModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryConfigScene/View/CalendarPickerFooterView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryConfigScene/View/CalendarPickerHeaderView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryConfigScene/View/Cell/CalendarDateCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryConfigScene/View/Cell/DiaryConfigCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryConfigScene/ViewController/CalendarPickerViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryConfigScene/ViewController/DiaryConfigViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/Model/MapCategory.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/Model/MyDiaryDaysModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/ViewController/MyDiaryDaysViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/HomeScene/View/Cell/DiaryCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/HomeScene/View/DiaryCollectionHeaderView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/HomeScene/ViewController/MyHomeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/View/TextStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/ViewController/PageEditModeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/ViewController/PageViewModeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/SignInScene/ViewController/SignInViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/ThumbnailConfigScene/ViewController/ThumbnailConfigViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/UserScene/ViewController/MyPageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/UserScene/ViewController/SetProfileImageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/UserScene/ViewModel/MyPageViewModel.swift
Labels: enhancement, D-2

#185 Fix/#182 UI screen 제거
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIKit/UIColor+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIKit/UIFont+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/UIKit/UIScreen+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Model/Layout.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/Common/View/AlbumCollectionView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/Common/View/Cell/MyAlbumCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/Common/ViewController/MapSearchViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/Common/ViewController/PopUpViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryConfigScene/View/CalendarPickerHeaderView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryConfigScene/View/Cell/CalendarDateCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryConfigScene/View/Cell/DiaryConfigCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryConfigScene/ViewController/CalendarPickerViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryConfigScene/ViewController/DiaryConfigViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/View/Cell/DiaryDaysCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/View/Cell/MapListCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/View/Cell/MyAlbumTitleCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/View/MapListView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/View/MapView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/View/PhotoCollectionView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/View/SegmentedControlView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/ViewController/MapListViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/ViewController/MyAlbumPhotoViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/ViewController/MyDiaryDaysViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/HomeScene/View/Cell/DiaryCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/HomeScene/View/CollectionEmptyView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/HomeScene/View/DiaryCollectionHeaderView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/HomeScene/View/DiaryCollectionView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/HomeScene/View/FilterButton.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/HomeScene/ViewController/MyHomeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/View/Cell/MapSearchResultTableViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/View/ImageStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/View/MapStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/View/StickerBorderView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/View/StickerContollerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/View/StickerStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/View/StickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/View/TextStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/ViewController/PageEditModeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/ViewController/PageViewModeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/ViewController/StickerPickerViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/SignInScene/ViewController/SignInViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/ThumbnailConfigScene/View/ThumbnailPreviewView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/ThumbnailConfigScene/ViewController/ThumbnailConfigViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/UserScene/View/Cell/MenuTableViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/UserScene/View/Cell/TravelsCollectionViewCell.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/UserScene/ViewController/MyPageViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/UserScene/ViewController/SetProfileImageViewController.swift
Labels: D-1, Refactor

#188 Fix/#181 이미지파일 업로드 시간으로 인한 데이터 버그 수정
  MacC-GoldenRatio/MacC-GoldenRatio.xcodeproj/project.pbxproj
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/YPImagePickerManager.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/DispatchGroup+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Extensions/Notification+.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Network/FirebaseStorage.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/Common/ViewModel/AlbumCollectionViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/DiaryDaysScene/Model/MyDiaryDaysModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/View/ImageStickerView.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/ViewController/PageEditModeViewController.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/ViewModel/PageEditModeViewModel.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/ViewModel/StickerViewData.swift
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/UserScene/ViewModel/MyPageViewModel.swift
Labels: bug, D-2

#192 [Design] #190 스티커 순서 수정
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/ViewController/StickerPickerViewController.swift
Labels: design, D-1

#193 Fix/#186 ImageManager 메모리 이슈 해결
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Classes/ImageManager.swift
Labels: bug, D-0

#195 [Fix] #194 StickerView 스티커 이동시 버그 수정
  MacC-GoldenRatio/MacC-GoldenRatio/Sources/Presenter/PageScene/View/StickerView.swift
Labels: bug, D-0
